import { Content } from "../types";

export const contents: Content[] = [
  {
    id: "1",
    source: "YouTube",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    title: "Never Gonna Give You Up",
    tags: ["music", "pop"],
    userId: "user1",
    createdAt: new Date("2023-10-01"),
  },
  {
    id: "2",
    source: "Tiktok",
    url: "https://www.tiktok.com/@example/video/1234567890",
    title: "Funny TikTok Video",
    tags: ["funny", "viral"],
    userId: "user2",
    createdAt: new Date("2023-10-02"),
  },
  {
    id: "3",
    source: "Instagram",
    url: "https://www.instagram.com/p/ExamplePost/",
    title: "Beautiful Sunset",
    tags: ["travel", "nature"],
    userId: "user3",
    createdAt: new Date("2023-10-03"),
  },
  {
    id: "8",
    source: "Reddit",
    url: "https://www.reddit.com/example/post/1234567890",
    title: "Why Most Startups failed...",
    tags: ["startup", "tech"],
    userId: "user7",
    createdAt: new Date("2023-10-05"),
    thumbnail: "https://via.placeholder.com/150/92c952",
    remindAt: new Date("2024-05-01T10:00:00"),
    isFavorite: true,
  },
  {
    id: "4",
    source: "Twitter",
    url: "https://x.com/example/status/1234567890",
    title: "Breaking News",
    tags: ["news"],
    userId: "user4",
    createdAt: new Date("2023-10-04"),
  },
  {
    id: "5",
    source: "Facebook",
    url: "https://www.facebook.com/example/post/1234567890",
    title: "Family Vacation Memories",
    tags: ["family", "travel"],
    userId: "user5",
    createdAt: new Date("2023-10-05"),
    thumbnail: "https://via.placeholder.com/150/92c952",
    remindAt: new Date("2024-05-01T10:00:00"),
    isFavorite: true,
  },
  {
    id: "6",
    source: "Medium",
    url: "https://medium.com/@example/how-to-learn-react",
    title: "How to Learn React Fast",
    tags: ["programming", "react", "javascript"],
    userId: "user6",
    createdAt: new Date("2023-10-06"),
    thumbnail: "https://via.placeholder.com/150/771796",
    remindAt: new Date("2024-05-02T15:00:00"),
    isFavorite: false,
  },
  {
    id: "7",
    source: "YouTube",
    url: "https://www.youtube.com/watch?v=5NV6Rdv1a3I",
    title: "Daft Punk - Get Lucky",
    tags: ["music", "funk", "live"],
    userId: "user7",
    createdAt: new Date("2023-10-07"),
    thumbnail: "https://via.placeholder.com/150/24f355",
    remindAt: new Date("2024-05-03T18:30:00"),
    isFavorite: true,
  },

  {
    id: "9",
    source: "Quora",
    url: "https://www.quora.com/What-is-the-meaning-of-life",
    title: "What is the meaning of life?",
    tags: ["philosophy", "life"],
    userId: "user8",
    createdAt: new Date("2023-10-08"),
    thumbnail: "https://via.placeholder.com/150/abc123",
    remindAt: new Date("2024-05-04T12:00:00"),
    isFavorite: false,
  },
  {
    id: "10",
    source: "LinkedIn",
    url: "https://www.linkedin.com/posts/example_post",
    title: "Top 10 Tips for Career Growth",
    tags: ["career", "growth", "business"],
    userId: "user9",
    createdAt: new Date("2023-10-09"),
    thumbnail: "https://via.placeholder.com/150/def456",
    remindAt: new Date("2024-05-05T09:00:00"),
    isFavorite: true,
  },
];
